### ISSUE TITLE
Gulp task for browser reload

### ISSUE THREAD

**Issue by marcosdourado** [quarq-solucoes/quarq-notes-template#40]
Create a task to reload the browser, whenever certain files are modified.

gulp serve - Unmemorable and non-concatenated files
gulp serves: dist - Files in the template that will be in production

you should be using this: https://browsersync.io/docs/gulp

**Comment by dyeimys** [comment]
@marcosdourado select project from this issue!

**Comment by marcosdourado** [comment]
@dyeimys  how is this done?
